# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "./..", "/vagrant"
  config.vm.provider :virtualbox do |v|
     v.customize ["modifyvm", :id, "--memory", 1048]
     # change this name as needed
     v.name = "bootstrip"
  end

  config.vm.provision :shell, path: "provision.sh"
  config.vm.network "forwarded_port", guest: 8020, host: 8020 
  config.vm.network "forwarded_port", guest: 8021, host: 8021 

end
