name: builds and deploys demo website
on: 
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    services:
        node:
          image: shukriadams/node12build:0.0.2
    steps:
      - uses: actions/checkout@v1
      - name: builds and copies static assets to remote Nginx folder
        run: cd src/build && sh ./build.sh 
        env:
            HOST: ${{ secrets.HOST }}
            USERNAME: ${{ secrets.USERNAME }}
            PASSWORD: ${{ secrets.PASSWORD }}
            CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }} 
            CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}
            CLOUDFLARE_APP: ${{ secrets.CLOUDFLARE_APP }}